services:
  - type: web
    name: skill-building-backend
    env: python
    region: oregon
    plan: free
    branch: ci/add-github-actions
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: HUGGINGFACEHUB_API_TOKEN
        sync: false
      - key: DATABASE_URL
        value: sqlite:///./skill_building.db
